TimeManager/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using TimeManager.Models;

namespace TimeManager.Controllers
{
    [Authorize]
    public class CategoriesController : BaseController
    {
        // GET: Category
        public ActionResult Index()
        {
            return View(CurrentUser.Categories);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View(new AddOrEditCategoryViewModel());
        }

        [HttpPost]
        public ActionResult Add(AddOrEditCategoryViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                MainRepository.AddCategory(CurrentUser,
                    new Category() {Name = viewModel.Name, Description = viewModel.Description});
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                var category = CurrentUser.Categories.First(x => x.CategoryId == id);
                return View(new AddOrEditCategoryViewModel() {CategoryId =  category.CategoryId, Name = category.Name, Description = category.Description});
            }
            return View();
        }

        [HttpPost]
        public ActionResult Edit(AddOrEditCategoryViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                MainRepository.UpdateCategory(CurrentUser, new Category(){CategoryId = viewModel.CategoryId, Name = viewModel.Name, Description = viewModel.Description});
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id.HasValue)
            {
                MainRepository.DeleteCategory(CurrentUser, CurrentUser.Categories.First(x => x.CategoryId == id));
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public string GetCurrentUserCategoriesAjax()
        {
            return JsonConvert.SerializeObject(CurrentUser.Categories.Select(x => new {x.CategoryId,x.Name}));
        }

        
    }
}

TimeManager/Controllers/TodosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using TimeManager.Models;

namespace TimeManager.Controllers
{
    [Authorize]
    public class TodosController : BaseController
    {
        // GET: Todo
        public ActionResult Index()
        {
            TodosModel todos = new TodosModel();

            var todaysTodos = from category in CurrentUser.Categories
                              from todo in category.Todos
                              where todo.StartDate.Date.Equals(DateTime.Today.Date)
                              select todo;
            var futureTodos = from category in CurrentUser.Categories
                              from todo in category.Todos
                              where todo.StartDate.Date > DateTime.Today.Date
                              select todo;
            todos.TodaysTodos.AddRange(todaysTodos);
            todos.FutureTodos.AddRange(futureTodos);
            return View(todos);
        }

        public ActionResult Add()
        {
            var model = new AddOrEditTodoViewModel();
            model.Categories = GetCategories();
            model.Priorities = GetPriorities();
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(AddOrEditTodoViewModel model)
        {
            if (ModelState.IsValid) {
                var category = CurrentUser.Categories.First(cat => cat.CategoryId == Int32.Parse(model.CategoryId));
                var endDate = DateTime.Now.AddDays(1);
                if (model.EndDate.HasValue)
                {
                    endDate = model.EndDate.GetValueOrDefault();
                }
                MainRepository.AddTodo(category,
                    new Todo()
                    {
                        ShortDescription = model.ShortDescription,
                        Description = model.Description,
                        StartDate = model.StartDate,
                        EndDate = endDate,
                        IsDone = model.IsDone,
                        Priority = Int32.Parse(model.Priotiry)
                    });
                return RedirectToAction("Index");
            }
            model.Categories = GetCategories();
            model.Priorities = GetPriorities();
            return View(model);
        }

        public ActionResult Detailed(int? id)
        {
            if (id.HasValue)
            {
                var todo = (from category in CurrentUser.Categories
                    from tmpTodo in category.Todos
                    where tmpTodo.TodoId == id
                    select tmpTodo).FirstOrDefault();
                if (todo != null)
                {
                    return View(todo);
                }
            }
            return View();
        }

        [HttpPost]
        public string AddAjax(AddTodoAjaxViewModel addTodoAjaxViewModelModel)
        {
            if (ModelState.IsValid)
            {
                var category = CurrentUser.Categories.First(cat => cat.Name == addTodoAjaxViewModelModel.CategoryName);
                var endDate = DateTime.Now.AddDays(1);
                if (addTodoAjaxViewModelModel.EndDate.HasValue)
                {
                    endDate = addTodoAjaxViewModelModel.EndDate.GetValueOrDefault();
                }
                MainRepository.AddTodo(category,new Todo() { ShortDescription = addTodoAjaxViewModelModel.ShortDescription, Description = addTodoAjaxViewModelModel.Description, StartDate = addTodoAjaxViewModelModel.StartDate, EndDate = endDate, IsDone = addTodoAjaxViewModelModel.IsDone, Priority = addTodoAjaxViewModelModel.Priority });
                ModelState.AddModelError("IsValid", "true");
                return JsonConvert.SerializeObject(ModelState);
            }
            return JsonConvert.SerializeObject(ModelState);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                var todo = (from category in CurrentUser.Categories
                    from tmpTodo in category.Todos
                    where tmpTodo.TodoId == id
                    select tmpTodo).FirstOrDefault();
                AddOrEditTodoViewModel viewModel = new AddOrEditTodoViewModel()
                {
                    TodoId = id.Value,
                    ShortDescription = todo.ShortDescription,
                    Description = todo.Description,
                    StartDate = todo.StartDate,
                    IsDone = todo.IsDone,
                    EndDate = todo.EndDate,
                    CategoryId = todo.Category.CategoryId.ToString(),
                    Priotiry = todo.Priority.ToString(),
                    Categories = GetCategories(),
                    Priorities = GetPriorities()
                };
                return View(viewModel);
            }
            return View();
        }

        [HttpPost]
        public ActionResult Edit(AddOrEditTodoViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var todo=CurrentUser.Categories.First(x => x.CategoryId == Int32.Parse(viewModel.CategoryId))
                        .Todos.First(t => t.TodoId == viewModel.TodoId);
                var newTodo = new Todo()
                {
                    TodoId = todo.TodoId,
                    ShortDescription = viewModel.ShortDescription,
                    Description = viewModel.Description,
                    StartDate = viewModel.StartDate,
                    IsDone = viewModel.IsDone,
                    EndDate = viewModel.EndDate.Value,
                    Category = CurrentUser.Categories.First(x => x.CategoryId == Int32.Parse(viewModel.CategoryId)),
                    Priority = Int32.Parse(viewModel.Priotiry)
                };
                
                MainRepository.UpdateTodo(CurrentUser,todo,newTodo);
                return RedirectToAction("Index");
            }
            viewModel.Categories = GetCategories();
            viewModel.Priorities = GetPriorities();
            return View(viewModel);
        }

        public ActionResult Delete(int? id)
        {
            if (id.HasValue)
            {
                var todo = (from category in CurrentUser.Categories
                    from tmpTodo in category.Todos
                    where tmpTodo.TodoId == id
                    select tmpTodo).First();
                MainRepository.RemoveTodo(todo);
            }
            return RedirectToAction("Index");
        }

        private SelectList GetCategories()
        {
            return new SelectList(from category in CurrentUser.Categories
                           select new
                           {
                               CategoryName = category.Name,
                               CategoryId = category.CategoryId.ToString(),

                           }, "CategoryId", "CategoryName");
        }

        private SelectList GetPriorities()
        {
            return new SelectList(from number in Enumerable.Range(1, 5)
                           select new
                           {
                               Text = number.ToString(),
                               Priority = number.ToString()
                           }, "Priority", "Text");
        }
    }
}

TimeManager/Views/AddTodoPartialView.cshtml
@using TimeManager.Models
@model TimeManager.Models.AddTodoAjaxViewModel
<div class="well add-todo-well">
    <div class="panel-heading well-header">
        Додати справу
    </div>
    <div class="panel-body add-todo-body">
        @using (Html.BeginForm("AddAjax", "Todos", FormMethod.Post, new {@class = "form-horizontal"}))
        {
            if (!Html.ValidationSummary().ToString().Contains("display:none"))
             {
                 <div class="alert alert-danger">
                     @Html.ValidationSummary()
                 </div>
             }
            <div class="form-group add-todo-group">
                @Html.EditorFor(m => m.ShortDescription, new { htmlAttributes = new { @class = "form-control", placeholder = "Короткий опис" } })
                <span class="text-danger" id="ShortDescriptionError"></span>
            </div>
            <div class="form-group add-todo-group">
                @Html.EditorFor(m => m.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "Детальний опис" } })
                <span class="text-danger" id="DescriptionError"></span>
            </div>
            <div class="form-group add-todo-group">
                <div class='input-group date' id='datetimepickerStart'>
                    <input type="text" class="form-control" id="StartDate" name="StartDate" placeholder="Початкова дата та час"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                <span class="text-danger" id="StartDateError"></span>
            </div>
            <div class="form-group add-todo-group">
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(m=>m.IsDone)
                        @Html.DisplayNameFor(x => x.IsDone)
                    </label>
                </div>
                <span class="text-danger" id="IsDoneError"></span>
            </div>
            <div class="form-group add-todo-group">
                <div class='input-group date' id='datetimepickerEnd'>
                    <input type="text" class="form-control" id="EndDate" name="EndDate" placeholder="Кінцева дата та час" disabled/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                <span class="text-danger" id="EndDateError"></span>
            </div>
            <div class="form-group add-todo-group" id="category-group">
                <select class="form-control" name="CategoryName" id="CategoryName" title="Оберіть категорію">
                    <option value="" selected disabled style='display: none;'>&lt;Категорія&gt;</option>
                </select>
                <span class="text-danger" id="CategoryError"></span>
            </div>
            <div class="form-group add-todo-group">
                <select class="form-control" id="Priority" name="Priority" title="Chose priority">
                    <option value="" selected disabled style='display: none;'>&lt;Пріоритет&gt;</option>
                    @for (int i = 1; i <= 5; i++)
                    {
                        <option value="@i">@i</option>
                    }
                </select>
                <span class="text-danger" id="PriorityError"></span>
            </div>
            <div class="form-group add-todo-group">
                <button id="AddTodoButton" class="btn btn-info form-control">Додати</button>
            </div>
        }
    </div>
</div>

TimeManager/Views/Header.cshtml
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="../">Time Manager</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="../">Головна сторінка</a></li>
                <li>@Html.ActionLink("Справи", "Index", "Todos")</li>
                <li>@Html.ActionLink("Категорії", "Index", "Categories")</li>
                <li>@Html.ActionLink("Контакти", "Contacts", "Home")</li>
            </ul>
        </div>
    </div>
</nav>

TimeManager/Views/UserLoginPartialView.cshtml
@model TimeManager.Models.LoginViewModel
@if (!ViewBag.IsAuthorized)
{
    <div class="well authorization-well">
        <div class="panel-heading well-header">
            Авторизація
        </div>
        <form class="form-horizontal">
            <div class="form-group authorization-group">
                <ul class="text-danger nomargin" id="CustomErrors"></ul>
                <div class="col-md-12">
                    @Html.EditorFor(m => m.UserName, new {htmlAttributes = new {@class = "form-control", placeholder = "Введіть e-mail"}})
                    <span class="text-danger" id="UserNameError"></span>
                </div>
            </div>
            <div class="form-group authorization-group">
                <div class="col-md-12">
                    @Html.EditorFor(m => m.Password, new {htmlAttributes = new {@class = "form-control", placeholder = "Введіть пароль", type = "password"}})
                    <span class="text-danger" id="PasswordError"></span>
                </div>
            </div>
            <div class="form-group authorization-group">
                <div class="col-md-12">
                    <button id="SignInButton" class="btn btn-info form-control">Ввійти</button>
                </div>
            </div>
        </form>
        <div class="panel-footer authorization-footer">
            @Html.ActionLink("Реєстрація","Register","Account")
            @Html.ActionLink("Забули пароль?", "ForgotPassword", "Account",null,new {@class = "pull-right"})
        </div>
    </div>
    <!--end authorization well-->
}
else
{
    <div class="well user-well">
        <div class="panel-heading well-header">
            Користувач
        </div>
        <div>Вітаємо, <a href="#">Олександр</a>!</div>
        <div>@Html.ActionLink("Вийти", "SignOut", "Account")</div>
    </div>
}